included:
  - ReactiveAu3dio
excluded:
  - Pods
opt_in_rules:
  - empty_count
  - force_unwrapping
  - private_outlet
  - vertical_whitespace
  # See https://github.com/realm/SwiftLint/issues/728
  # - missing_docs
disabled_rules:
  - line_length
  - variable_name
