language: generic
sudo: required
dist: trusty
matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode8
      xcode_workspace: ReactiveAu3dio.xcworkspace
      xcode_scheme: ReactiveAu3dioTests
