os: osx
sudo: required
osx_image: xcode8.2
language: generic

env:
  global:
    - ROCK_PATH="$HOME/.rock" # default
    - PATH="$PATH:./.rock/bin:$ROCK_PATH/bin"

install:
  - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
  - curl -sL https://raw.githubusercontent.com/vknabel/Rock/master/Scripts/Install.generated.swift | swift -
  - rock run prepare

script:
  - set -o pipefail
  - rock test
  - rock run lint

cache:
  - bundler
  - cocoapods
  - directories:
    - .rock
    - $HOME/.swiftenv
    - $HOME/.rock
